
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_RMI4_I2C) += synaptics_dsx_i2c.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_RMI4_DSX_DEV) += synaptics_dsx_rmi_dev.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_RMI4_FW_UPDATE) += synaptics_dsx_fw_update.o
